apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vancouver-grizzlies-db
  labels:
    app: vancouver-grizzlies-db
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: vancouver-grizzlies-db
  endpoints:
  - port: http
    path: /metrics
